import type { Metadata } from "next";
import "./globals.css";
import Button from "@mui/material/Button";
import TimelineIcon from "@mui/icons-material/Timeline";
import { Divider } from "@mui/material";
import Link from "next/link";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
